### ISSUE TITLE
does it work on linux?

### ISSUE THREAD

**Issue by codegod100** [Scthe/nanite-webgpu#3]
I'm on fedora using google chrome and it says no webgpu

**Comment by danielcherubini** [comment]
enable the webgpu using flags, ` --enable-unsafe-webgpu --enable-features=Vulkan`
or do the same in `chrome://flags/`

**Comment by Scthe** [comment]
I don't have an access to Linux ATM, but (as Daniel Cherubini mentioned) is seems there are some Chrome flags: [https://github.com/gpuweb/gpuweb/wiki/Implementation-Status](https://github.com/gpuweb/gpuweb/wiki/Implementation-Status).

**Comment by codegod100** [comment]
that worked!
