### ISSUE TITLE
RGBA32Float blending is used, but not supported by WebGPU

### ISSUE THREAD

**Issue by mwyrzykowski** [Scthe/nanite-webgpu#5]
WebGPU does not support blending on 32-bits per channel RGBA floating point textures, see the chart https://gpuweb.github.io/gpuweb/#plain-color-formats :

<img width="1114" alt="Screenshot 2024-09-06 at 11 52 59 AM" src="https://github.com/user-attachments/assets/46388e1c-18cd-481a-a93d-ff0e52e219ca">

However it appears Nanite is attempting to do so: https://github.com/Scthe/nanite-webgpu/blob/a562d80df3da237034bee62d97d87bce0db04967/src/constants.ts#L50C1-L51C1

This is causing a validation error opening https://scthe.github.io/nanite-webgpu/?scene_file=jinxCombined&impostors_threshold=4000&softwarerasterizer_threshold=1360&nanite_errorthreshold=0.1 in Safari / WebKit. 

WebKit has one other bug, fixed by https://bugs.webkit.org/show_bug.cgi?id=279266, but with that fix and working around the rgba32float blending issue described here, it appears the [nanite demo](https://scthe.github.io/nanite-webgpu/?scene_file=jinxCombined&impostors_threshold=4000&softwarerasterizer_threshold=1360&nanite_errorthreshold=0.1) works in Safari WebKit as well, at least on macOS:
![Screenshot 2024-09-06 at 11 06 23 AM](https://github.com/user-attachments/assets/f84ee889-91d9-4a66-b62a-9bdbf3d24fb4)

**Comment by Scthe** [comment]
So for my part, would `export const HDR_RENDER_TEX_FORMAT: GPUTextureFormat = 'rgba16float';` be enough? I see I already changed this in [Frostbitten hair WebGPU](https://github.com/Scthe/frostbitten-hair-webgpu/blob/master/src/constants.ts#L35), wish I remembered why.

**Comment by mwyrzykowski** [comment]
Yes I think so, I don't see any other usages for rgba32float. 

I haven't gotten around to building it from source, I just tried the live demo on WebKit's main development branch. So it should also work great in Safari Technology Preview once https://bugs.webkit.org/show_bug.cgi?id=279266 lands in a build, which is usually a few weeks from the point the fix was merged (today).

**Comment by Scthe** [comment]
Fixed in https://github.com/Scthe/nanite-webgpu/commit/64b5471e39c91604fa81dd098ec296a2debd17fe, should be already deployed. No matter how much I **HATE** the person who posted this repo on Hacker News, at least something good (your fix) resulted from the whole ordeal.

**Comment by mwyrzykowski** [comment]
Confirmed it's working with your fix and WebKit's on ToT WebKit (macOS with MiniBrowser) - thank you!
