### ISSUE TITLE
doesn't run in Firefox

### ISSUE THREAD

**Issue by pjbaron** [Scthe/nanite-webgpu#6]
This is wonderful in Chrome, but in Firefox I get:

20:27:50.946 Uncaught ReferenceError: GPUBufferUsage is not defined
    <anonymous> webgpu.ts:46
    <anonymous> index.web.ts:290
webgpu.ts:46:2

**Comment by pjbaron** [comment]
Apologies, should have checked closed issues first!

**Comment by ErichDonGubler** [comment]
For anybody who's interested: Firefox is tracking this at [bug 1917099](https://bugzilla.mozilla.org/show_bug.cgi?id=1917099). Looks like it's close to working! 😀

**Comment by Scthe** [comment]
I've added detailed overview in https://github.com/Scthe/nanite-webgpu/issues/4#issuecomment-2471602435.
